Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,18 +32,18 @@ jobs:
           echo "provider = Cloudflare" >> /tmp/rclone.conf
           echo "access_key_id = ${{ secrets.r2.R2_ACCESS_KEY_ID }}" >> /tmp/rclone.conf
           echo "secret_access_key = ${{ secrets.r2.R2_SECRET_ACCESS_KEY }}" >> /tmp/rclone.conf
-          echo "endpoint = ${{ secrets.r2.R2_ENDPOINT }}" >> /tmp/rclone.conf
+          echo "bucket = ${{ vars.r2.R2_BUCKET }}" >> /tmp/rclone.conf
 
       - name: Upload to Cloudflare R2
         run: |
           echo "Uploading to Cloudflare R2..."
-          rclone copy ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip r2:${{ secrets.r2.R2_BUCKET }} --config /tmp/rclone.conf -vv --dump-bodies --retries 1 || echo "Upload failed with exit code $?"
+          rclone copy ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip r2:${{ vars.r2.R2_BUCKET }} --config /tmp/rclone.conf -vv --dump-bodies --retries 1 || echo "Upload failed with exit code $?"
         env:
           ZIP_FILE: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip
 
       - name: Post to Discord
         if: success()
         run: |
-          FILE_URL="${{ secrets.r2.R2_ENDPOINT }}/${{ secrets.r2.R2_BUCKET }}/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip"
+          FILE_URL="${{ secrets.r2.R2_ENDPOINT }}/${{ vars.r2.R2_BUCKET }}/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.sha }}.zip"
           echo "Posting to Discord..."
           curl -H "Content-Type: application/json" -d "{\"content\": \"New release available: $FILE_URL\"}" ${{ secrets.r2.DISCORD_WEBHOOK_URL }}
